# fly.toml app configuration file generated for flask-quick on 2025-05-20T19:10:48-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flask-quick'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
